pipeline {
    agent any

    environment {
        AWS_DEFAULT_REGION = 'your-aws-region'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    sh 'terraform init -input=false'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    sh 'terraform plan -out=tfplan -input=false'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    sh 'terraform apply -input=false -auto-approve tfplan'
                }
            }
        }

        stage('Terraform Destroy') {
            steps {
                script {
                    // Uncomment and use this stage carefully, as it will destroy resources
                    // sh 'terraform destroy -auto-approve'
                }
            }
        }
    }

    post {
        always {
            // Clean up after the build
            script {
                sh 'rm -rf .terraform tfplan terraform.tfstate*'
            }
        }
    }
}
